"""Initial migration

Revision ID: aa4056bb97f2
Revises: 
Create Date: 2024-09-21 19:00:10.127127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'aa4056bb97f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('total_pages', sa.Integer().with_variant(sa.Numeric(precision=10, scale=0), 'mssql'), nullable=False),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('author_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('authors')
    # ### end Alembic commands ###
